### ISSUE TITLE
资源目录根节点增加是否展示配置

### ISSUE THREAD

**Issue by yiziyu007** [SuperMap/GAF#35]
![image](https://user-images.githubusercontent.com/78577162/116501161-b5bbef80-a8e2-11eb-9a09-f048bb576292.png)
在展示资源目录的时候，有时候不用展示出根目录，减少资源目录树的层级

**Comment by yiziyu007** [comment]
例如自然资源数据目录体系
 --现状数据
--规划管控数据
--管理数据
--社会经济数据

**Comment by yifu-du** [comment]
下个版本实现
