### ISSUE TITLE
资源目录树添加bug

### ISSUE THREAD

**Issue by yiziyu007** [SuperMap/GAF#36]
在资源目录树上新增子目录，点击一个新的节点首次加载的还是上一个节点的子目录，新增节点后才展示当前节点的子目录

**Comment by yiziyu007** [comment]
![image](https://user-images.githubusercontent.com/78577162/116501967-cbcaaf80-a8e4-11eb-9720-6e816518be78.png)

**Comment by yifu-du** [comment]
已做刷新处理
